# Generated by Django 4.1.4 on 2023-12-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_test_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
