# Generated by Django 4.1.4 on 2024-01-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_testprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testprice',
            name='speaking',
        ),
        migrations.RemoveField(
            model_name='testprice',
            name='writing',
        ),
    ]
