# Generated by Django 4.1.4 on 2024-01-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0003_teacher_speaking_price_teacher_writing_price'),
        ('exam', '0003_remove_testprice_speaking_remove_testprice_writing'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('general', 'general')], max_length=128)),
                ('test_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('general', 'general')], max_length=128)),
                ('test_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.reservetimes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
