# Generated by Django 4.1.4 on 2023-12-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_test_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
    ]
