# Generated by Django 4.1.4 on 2023-12-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
