# Generated by Django 4.1.4 on 2024-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_writingtest_speakingtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtest',
            name='task1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='task2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
