# Generated by Django 4.1.4 on 2024-02-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_speakingtest_amount_speakingtest_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtest',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='authority',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('zibal', 'zibal'), ('zarinpal', 'zarinpal'), ('manual', 'manual')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('canceled', 'canceled'), ('paid', 'paid')], default='new', max_length=128),
        ),
    ]
