# Generated by Django 4.1.4 on 2024-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_testhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
