# Generated by Django 4.1.4 on 2024-02-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_testhistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='confirm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
