# Generated by Django 4.1.4 on 2024-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_test_full_report_authority_test_full_report_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='full_report_ref_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
