# Generated by Django 4.1.4 on 2024-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_test_full_report_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='media_report_authority',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='media_report_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='media_report_ref_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
