# Generated by Django 4.1.4 on 2024-05-07 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0013_test_media_report_authority_test_media_report_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('note', 'note'), ('highlight', 'highlight')], max_length=10)),
                ('range', models.CharField(blank=True, max_length=128, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
