# Generated by Django 4.1.4 on 2024-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtest',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speakingtest',
            name='confirm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writingtest',
            name='confirm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
