# Generated by Django 4.1.4 on 2024-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='speaking_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='writing_price',
            field=models.IntegerField(default=0),
        ),
    ]
