# Generated by Django 4.1.4 on 2024-01-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('skill', models.CharField(choices=[('listening', 'listening'), ('reading', 'reading'), ('writing', 'writing')], max_length=128)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('general', 'general')], max_length=128)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
