# Generated by Django 4.1.4 on 2024-05-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaanswer',
            name='audio',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mediaanswer',
            name='video',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
