# Generated by Django 4.1.4 on 2024-02-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_product_listening_remove_product_reading_and_more'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFullCorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('skill', models.CharField(choices=[('listening', 'listening'), ('reading', 'reading'), ('writing', 'writing')], max_length=128)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('general', 'general')], max_length=128)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=256, null=True)),
                ('question', models.CharField(blank=True, max_length=256, null=True)),
                ('keywords', models.CharField(blank=True, max_length=256, null=True)),
                ('fuul_answer', models.TextField(blank=True, max_length=2500, null=True)),
                ('test_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.testfullcorrectanswer')),
            ],
        ),
    ]
