# Generated by Django 4.1.4 on 2024-02-24 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_rename_fuul_answer_answer_full_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
