# Generated by Django 4.1.4 on 2024-02-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_answer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='full_answer',
        ),
    ]
