# Generated by Django 4.1.4 on 2024-02-26 03:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_answer_full_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.AlterField(
            model_name='answer',
            name='full_answer',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2500, null=True),
        ),
    ]
