# Generated by Django 4.1.4 on 2024-03-12 07:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0007_remove_answer_content_alter_answer_full_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='full_answer',
            field=ckeditor.fields.RichTextField(blank=True, max_length=7000, null=True),
        ),
    ]
