# Generated by Django 4.1.4 on 2024-03-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_product_listening_remove_product_reading_and_more'),
        ('answers', '0008_alter_answer_full_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMediaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('skill', models.CharField(choices=[('listening', 'listening'), ('reading', 'reading'), ('writing', 'writing')], max_length=128)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('general', 'general')], max_length=128)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('video', models.FileField(upload_to='video_answer')),
                ('audio', models.FileField(upload_to='audio_answer')),
                ('test_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.testmediaanswer')),
            ],
        ),
    ]
