# Generated by Django 4.1.4 on 2023-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(default=1, upload_to='books'),
            preserve_default=False,
        ),
    ]
