# Generated by Django 4.1.4 on 2024-01-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('skill', models.CharField(choices=[('listening', 'listening'), ('reading', 'reading'), ('writing', 'writing')], max_length=128)),
                ('type', models.CharField(choices=[('academic', 'academic'), ('general', 'general')], max_length=128)),
                ('enable', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
