# Generated by Django 4.1.4 on 2024-01-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_book_cover_photo_book_academic_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='academic_cover_photo',
            field=models.ImageField(default='books/default.png', upload_to='books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='general_cover_photo',
            field=models.ImageField(default='books/default.png', upload_to='books'),
        ),
    ]
