# Generated by Django 4.1.4 on 2024-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_academic_cover_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skill',
        ),
        migrations.AddField(
            model_name='product',
            name='listening',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reading',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='writing',
            field=models.BooleanField(default=True),
        ),
    ]
