# Generated by Django 4.1.4 on 2024-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_product_listening_remove_product_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='academic_cover_photo',
            field=models.ImageField(default='books/default.png', upload_to='https://ieltsways2.storage.iran.liara.space/media/books/'),
        ),
    ]
