# Generated by Django 4.1.4 on 2024-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_academic_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='academic_cover_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
