# Generated by Django 4.1.4 on 2023-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('canceled', 'canceled'), ('paid', 'paid')], default='new', max_length=128),
        ),
    ]
