# Generated by Django 4.1.4 on 2024-01-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_manual_payment_receipt_manualpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='transaction_photo',
            field=models.ImageField(blank=True, null=True, upload_to='transaction'),
        ),
    ]
