# Generated by Django 4.1.4 on 2024-02-01 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0007_speakingtest_score_writingtest_amount_and_more'),
        ('order', '0005_speakingmanualpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_photo', models.ImageField(blank=True, null=True, upload_to='transaction')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.writingtest')),
            ],
        ),
    ]
