# Generated by Django 4.1.4 on 2024-02-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_manualpayment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpayment',
            name='transaction_photo',
        ),
        migrations.RemoveField(
            model_name='speakingmanualpayment',
            name='transaction_photo',
        ),
        migrations.RemoveField(
            model_name='writingmanualpayment',
            name='transaction_photo',
        ),
    ]
