name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 195.214.235.46
          username: root
          password: dssdvSDVSDVqwc21
          script: |
            cd ~/../IELTSWays/Back-End/
            git pull
            docker-compose up -d --build
